services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/var/www/html/app
      - node_modules:/var/www/html/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "cd app && npm install && npm run dev"
volumes:
  node_modules:
